# ======================================================================== #
# Configuration for Moonlit Network Core   This is a test msg              #
# ======================================================================== #

# Settings related to the automatic update checker and downloader.
updater:
  # Set to true to automatically check for updates when the server starts.
  check-on-startup: true

  # Set to true to automatically download new versions if found.
  # The update will be placed in the '/plugins/update/' folder and will
  # require a full server RESTART to be applied.
  download-updates: true

  # --- GitHub Repository Details ---

  # Your GitHub username or the name of the organization that owns the repository.
  github-owner: "Daniel-Farmer"   # <-- Your GitHub Username

  # The name of the repository on GitHub where the plugin code and releases are hosted.
  github-repo: "moonlit-network"    # <-- Your GitHub Repository Name

  # --- JAR Asset Name (CRITICAL) ---
  # The EXACT filename of the JAR file asset that you attach to your releases on GitHub.
  # This MUST match the file generated by 'mvn package' (e.g., moonlit-network-1.0.jar).
  # This is case-sensitive.
  jar-asset-name: "moonlit-network-1.2.jar" # <-- Updated based on your build output screenshot

  # --- Notifications ---

  # Set to true to notify online players who have the 'moonlit.admin.notify' permission
  # when an update is found or downloaded. Messages are always sent to the console regardless.
  notify-admins: true

# ======================================================================== #
# Add other plugin configuration sections below if needed in the future.   #
# ======================================================================== #